<?php if (!$this->singleAlbumMode || $this->pagesCount > 1): ?>
<div class="ui-controls">
    <?php if (!$this->singleAlbumMode): ?>
    <a data-action="navigation-up" href="<?=$this->e($this->url('index'))?>">← <?=$this->e($this->album)?></a>
    <?php endif; ?>

        <?php if ($this->imagesCount > 1 || true) : ?>
        <a data-action="navigation-random" id="navigation-random" href="<?=$this->e($this->url('random', array('album' => $this->album)))?>">rand</a>
        <?php endif; ?>

         <!--(<?=$this->e($this->imagesCount)?>)-->
    <?php if ($this->pagesCount > 1): ?>
        <?php for ($i = 1; $i <= $this->pagesCount; $i++): ?>
            <?php
            $params = array();

            if ($this->album !== '') {
                $params['album'] = $this->album;
            }

            if ($i > 1) {
                $params['page'] = $i;
            }

            $link   = $this->url('album', $params);
            $active = ($i === $this->activePage) ? ' class="active"' : '';
            $linkId = '';
            $foo    = array();

            if ($i === $this->nextPageNumber)     { $foo[] = 'navigation-next';     }
            if ($i === $this->previousPageNumber) { $foo[] = 'navigation-previous'; }
            if (count($foo) > 0) { $linkId = ' data-action="' . implode(' ', $foo) . '"'; }
            ?>
            <a<?=$linkId?><?=$active?> href="<?=$this->e($link)?>"><?=$i?></a>
        <?php endfor; ?>
    <?php endif; ?>
</div>
<?php endif; ?>

<div class="ui-content cf">
    <?php $first = true; ?>
    <ul>
    <?php foreach ($this->images as $bild) : ?>
        <?php
        $webPath1 = $this->url('detail', array(
            'album'    => $this->album,
            'filename' => $bild->getBasename()
        ));

        $webPath = $this->url('image', array(
            'album'    => $this->album,
            'filename' => $bild->getBasename(),
            'element'  => 'thumb'
        ));
        ?>

        <li>
            <div class="image-container">
            <?php
            $title = implode("\n", array(
                $bild->getBasename()
            ));
            /*
            $title = implode("\n", array(
                $bild->getBasename(),
                $bild->getWidth() . ' × ' . $bild->getHeight() . ' pixels',
                round($bild->getFileSize() / 1000) . ' kB',
                ($bild->getCreationDate() === null) ? 'unknown' : $bild->getCreationDate()->format('Y-m-d H:i:s'),
                $bild->getFilemdate()->format('Y-m-d H:i:s')
            ));
            */
            ?>

            <a<?=($first)?' data-action="navigation-detail"':''?> href="<?=$this->e($webPath1)?>" title="<?=$this->e($title)?>">
                <img src="<?=$this->e($webPath)?>" />
            </a>
            </div>
        </li>

        <?php $first = false; ?>
    <?php endforeach ?>
    </ul>
</div>
