<?php
$params = array();

if ($this->album !== '') {
    $params['album'] = $this->album;
}

if ($this->page > 1) {
    $params['page'] = $this->page;
}

$url = $this->url('album', $params);
?>

<div class="ui-controls-wrapper">
    <div class="ui-controls">

        <a data-action="navigation-up" href="<?=$this->e($url)?>">
            ←
            <?php if ($this->album !== ''): ?>
                <?=$this->e($this->album)?>
            <?php endif; ?>
        </a>

        <?php if (count($this->images) > 1): ?>
            <a data-action="navigation-random" id="navigation-random" href="<?=$this->e($this->url('random', array('album' => $this->album)))?>">rand</a>
        <?php endif; ?>

        <?php if ($this->prevImageUrl !== ''): ?>
            <a data-action="navigation-previous" href="<?=$this->e($this->prevImageUrl)?>">«</a>
        <?php endif; ?>

        <?php if ($this->nextImageUrl !== ''): ?>
            <a data-action="navigation-next" href="<?=$this->e($this->nextImageUrl)?>">»</a>
        <?php endif; ?>

        <?=$this->e($this->filename)?>
        (<?=$this->e($this->i + 1)?>/<?=$this->e(count($this->images))?>)

    </div>
</div>

<div class="detail-container">
    <?php if ($this->nextImageUrl !== ''): ?>
        <a href="<?=$this->e($this->nextImageUrl)?>">
    <?php endif; ?>

    <img class="detail-image" src="<?=$this->e($this->imageUrl)?>" title="<?=$this->e($this->filename)?>">

    <?php if ($this->nextImageUrl !== ''): ?>
        </a>
    <?php endif; ?>
</div>
