<?php

/** @var \mermshaus\fine\model\ViewModelLayout $this */

$htmlId = ($this->getHtmlId() === null) ? '' : $this->getHtmlId();

$versionString = $this->getAppVersion() . '-' . filemtime(__FILE__);

$scripts = array(
    'jquery-1.12.4.min.js',
    'jquery.mobile.custom.min.js',
    'fine.js'
);

$scriptsHtml = '';

foreach ($scripts as $script) {
    $scriptsHtml .= sprintf('<script src="%s" defer></script>',
        $this->e($this->url('asset', array('file' => $script, 'v' => $versionString)))
    );
}

$stylesHtml = sprintf('<link href="%s" rel="stylesheet">',
    $this->e($this->url('asset', array('file' => 'fine.css', 'v' => $versionString)))
);

?><!DOCTYPE html>
<html lang="en"<?=($htmlId !== '') ? ' id="' . $this->e($htmlId) . '"' : '';?>>
<head>
    <meta charset="utf-8">
    <title>Fine Image Gallery</title>
    <meta name="description" content="A gallery of fine images.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?=$scriptsHtml?>
    <?=$stylesHtml?>
</head>
<body>
    <?php $this->getContentView()->output(); ?>

    <?php if ($htmlId === 'page-index' || $htmlId === 'page-album'): ?>
        <div id="fine-logo">
            <p>
                <span class="fine-logo-title"><a href="https://github.com/mermshaus/fine/releases">ﬁne image gallery</a></span><br>
                <span class="fine-logo-version">v<?=$this->e($this->getAppVersion())?></span><br>
            </p>
        </div>
        <div id="fine-scrolltop" data-action="navigation-scrolltop" class="active-javascript">↑</div>
    <?php endif; ?>
</body>
</html>
