<?php

/** @var \mermshaus\fine\model\ViewModelStatus $this */

$f = function ($s) {
    if ($s > 0) {
        return $this->e($s);
    }

    return '&nbsp;';
};

$formatFileSize = function ($s) {
    if ($s > 0) {
        return $this->e(number_format($s / 1000000, 1));
    }

    return '&nbsp;';
};

?>

<div class="ui-controls">
    <a data-action="navigation-up" href="<?=$this->e($this->url('index'))?>">← <?=$this->e('Status page')?></a>
</div>

<div class="ui-content">

<pre><?=$this->e($this->getOutput())?></pre>

<table>
    <tr>
        <th rowspan="3">Basename</th>
        <th rowspan="3">Path</th>
        <th rowspan="3">Directories</th>
        <th rowspan="3">Files</th>
        <th rowspan="3">Size</th>
        <th colspan="<?=(count($this->getPrefixes()) * 2)?>">Cache</th>
    </tr>
    <tr>
        <?php foreach ($this->getPrefixes() as $prefix): ?>
            <th colspan="2"><?=$this->e($prefix)?></th>
        <?php endforeach; ?>
    </tr>
    <tr>
        <?php foreach ($this->getPrefixes() as $prefix): ?>
            <th>Count</th>
            <th>Size</th>
        <?php endforeach; ?>
    </tr>

    <?php foreach ($this->getInfo() as $info): ?>

    <tr>
        <td><a href="<?=$this->e($this->url('index', ['path' => $info->path]))?>"><?=$this->e($info->basename)?></a></td>
        <td><?=$this->e($info->path)?></td>
        <td><?=$info->directoryCount > 0 ? $this->e($info->directoryCount) : '&nbsp;'?></td>
        <td><?=$this->e($info->fileCount)?></td>
        <td><?=$this->e($formatFileSize($info->size))?></td>
    </tr>

    <?php endforeach; ?>

    <?php /*
<?php foreach ($this->getInfo() as $data): ?>

<tr>
    <td><a href="<?=$this->e($this->url('album', array('album' => $album)))?>"><?=$this->e(($album !== '') ? $album : 'link')?></a></td>
    <td class="text-right"><?=$f($data['count'])?></td>
    <td class="text-right"><?=$formatFileSize($data['size'])?></td>
    <?php foreach ($this->getPrefixes() as $prefix): ?>
        <td class="text-right"><?=$f($data['cache'][$prefix]['count'])?></td>
        <td class="text-right"><?=$formatFileSize($data['cache'][$prefix]['size'])?></td>
    <?php endforeach; ?>
</tr>

<?php endforeach; ?>

<tr>
    <td class="text-right">&sum;</td>
    <td class="text-right"><?=$f($sums['count'])?></td>
    <td class="text-right"><?=$formatFileSize($sums['size'])?></td>
    <?php foreach ($this->getPrefixes() as $prefix): ?>
        <td class="text-right"><?=$f($sums['cache'][$prefix]['count'])?></td>
        <td class="text-right"><?=$formatFileSize($sums['cache'][$prefix]['size'])?></td>
    <?php endforeach; ?>
</tr>

 */ ?>

</table>

</div>
